[package]
name = "hive-utilities-library"
version = "1.1.0"
edition = "2024"
description = "A standard utilities library for the Hive ecosystem"
license = "Mozilla Public License 2.0"

[lib]
name = "hive_library"
path = "sources/library.rs"

[[bin]]
name = "hive_tester"
path = "sources/tester.rs"

[features]
default = [
	"ciborium",
	"bincode",
	"json"
]
ciborium = [
	"dep:ciborium"
]
bincode = [
	"dep:bincode"
]
json = [
	"dep:serde_json"
]

[dependencies]
serde = {
    version = "1.0.229",
    features = [
        "derive"
    ]
}
ciborium = {
	version = "0.2.2",
	optional = true
}
bincode = {
	version = "2.0.1",
	features = [
		"serde"
	],
	optional = true
}
serde_json = {
	version = "1.0.151",
	optional = true
}

toml = "1.1.4"

tokio = {
    version = "1.53.1",
    features = [
        "full"
    ]
}

sudo2 = "0.2.1"

nix = {
	version = "0.31.3",
	features = [
		"fs",
		"process",
		"signal",
		"socket",
		"term"
	]
}
